DROP DATABASE IF EXISTS CAR_RENTAL_GATEWAY;
CREATE DATABASE CAR_RENTAL_GATEWAY;
USE CAR_RENTAL_GATEWAY;

CREATE TABLE BOOKING (
    booking_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    distributor_id INT(6),
    booking_name VARCHAR(30),
    location VARCHAR(100)
);

DROP DATABASE IF EXISTS USA_CUSTOMER;
CREATE DATABASE USA_CUSTOMER;
USE USA_CUSTOMER;

CREATE TABLE USER (
    user_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(30) NOT NULL,
    home_address VARCHAR(30),
    email_address VARCHAR(50),
    date_of_birth TIMESTAMP,
    telephone_number VARCHAR(10)
)